### ISSUE TITLE
Test timeout with nx and vitest

### ISSUE THREAD

**Issue by EQuincerot** [DataDog/test-visibility-install-script#21]
I am working on a ts single repository with one node app and multiple ts packages.
We run unit test with `nx affected "test:ci"`, where the `test:ci` target runs : `vitest run --coverage.enabled`.

When using the `NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}`, one project time outs (>10min). It occurs only in github and only on one of the package. 

When removing the `--import` NODE_OPTIONS, everything works fine.

If we enable `--output-style=stream` nx option, we see that all tests are properly run individually and successful, but the run report summarizing the time spent to run the test is missing.

It's a bit hard to get more details about the error as it cannot be reproduced locally.

Is there any option that could help to debug the issue with the `--import`?

**Comment by juan-fernandez** [comment]
hey @EQuincerot thanks for the report. 

Could you provide the configuration of your github action? Specifically the part executing `nx affected "test:ci"`. You can remove any sensitive data. 

Additionally, off the top of my head, passing `NODE_OPTIONS` to `nx` is likely to be problematic, as `NODE_OPTIONS` is interpreted by every node.js process. Is there any way for you to pass `NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}` _just to vitest_ ?

**Comment by EQuincerot** [comment]
The workflow contains mostly:

```
      - name: Run unit test across affected packages
        id: unit-test
        run: ${{ env.NX_RUN_COMMAND }} test:ci
        env:
          NODE_OPTIONS: -r ${{ env.DD_TRACE_PACKAGE }} --import ${{ env.DD_TRACE_ESM_IMPORT }}
```

where `NX_RUN_COMMAND="npx nx affected -t"`

and `test:ci` target is defined as followed in each `package.json`

```
    "test:ci": "vitest run --coverage.enabled",
```

---

I just tried to pass the node options only to `vitest`, but I have the same result.

```
      - name: Run unit test across affected packages
        id: unit-test
        run: ${{ env.NX_RUN_COMMAND }} test:ci
```
and `package.json`:

```
    "test:ci": "NODE_OPTIONS=\"-r $DD_TRACE_PACKAGE --import $DD_TRACE_ESM_IMPORT\" vitest run --coverage.enabled",
```

But I face to the same issue.
